export default [
	{
		bookingId: 'CIARZ96',
		roomNumber: '109',
		guestName: 'Lalit Verma',
		checkInDate: '25 Jul 2022',
		checkOutdate: '26 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Tilalverma.lv@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '26/07/2022 06:40:37',
				approvalStatus: 'APPROVED',
				approvedTime: '26/07/2022, 12:44:39',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZC7',
		roomNumber: '109',
		guestName: 'Lalit Verma',
		checkInDate: '25 Jul 2022',
		checkOutdate: '27 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Tilalverma.lv@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '26/07/2022 11:26:51',
				approvalStatus: 'APPROVED',
				approvedTime: '26/07/2022, 16:59:28',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZES',
		roomNumber: '109',
		guestName: 'Lalit Verma',
		checkInDate: '26 Jul 2022',
		checkOutdate: '27 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Tilalverma.lv@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '26/07/2022 11:47:08',
				approvalStatus: 'APPROVED',
				approvedTime: '26/07/2022, 17:17:33',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARYTU',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '20 Jul 2022',
		checkOutdate: '31 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 04:57:46',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 10:30:28',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZIH',
		roomNumber: '109',
		guestName: 'Lalit Verma',
		checkInDate: '27 Jul 2022',
		checkOutdate: '28 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Tilalverma.lv@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 06:07:42',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 13:50:38',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARY72',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '18 Jul 2022',
		checkOutdate: '31 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '26/07/2022 12:09:52',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 13:59:30',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZ9A',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '25 Jul 2022',
		checkOutdate: '28 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 10:09:50',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 15:43:54',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZIF',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '27 Jul 2022',
		checkOutdate: '29 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 04:51:13',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 16:01:06',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZ98',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '25 Jul 2022',
		checkOutdate: '31 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 10:35:48',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 16:06:34',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZEQ',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '26 Jul 2022',
		checkOutdate: '29 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 10:38:30',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 16:09:54',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZBM',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '25 Jul 2022',
		checkOutdate: '28 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '27/07/2022 11:18:19',
				approvalStatus: 'APPROVED',
				approvedTime: '27/07/2022, 16:48:52',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZKF',
		roomNumber: '109',
		guestName: 'Lalit Verma',
		checkInDate: '27 Jul 2022',
		checkOutdate: '31 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Tilalverma.lv@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '28/07/2022 08:43:46',
				approvalStatus: 'APPROVED',
				approvedTime: '28/07/2022, 14:22:08',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZR4',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '28 Jul 2022',
		checkOutdate: '29 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '28/07/2022 09:30:39',
				approvalStatus: 'REJECTED',
				approvedTime: '28/7/2022, 3:26:50 PM',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZTL',
		roomNumber: '109',
		guestName: 'ANANDHU A',
		checkInDate: '28 Jul 2022',
		checkOutdate: '30 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'anandhu17.6@gmail.com',
				guestType: 'PRIMARY',
				requestedOn: '28/07/2022 01:07:42',
				approvalStatus: 'APPROVED',
				approvedTime: '7/28/2022, 6:45:56 PM',
				approvedBy: 'jumeirahmindtree@gmail.com',
			},
		],
	},
	{
		bookingId: 'CIARZYD',
		roomNumber: '109',
		guestName: 'Mindtree Test',
		checkInDate: '29 Jul 2022',
		checkOutdate: '31 Jul 2022',
		mobileKeyRequested: 1,
		mobileKeyIssued: 1,
		userDetails: [
			{
				emailId: 'Dxpplatform.Appsupport@mindtree.com',
				guestType: 'PRIMARY',
				requestedOn: '29/07/2022 11:49:51',
				approvalStatus: 'REJECTED',
				approvedTime: '7/29/2022, 5:44:31 PM',
				approvedBy: 'mindtreemobiledh@gmail.com',
			},
		],
	},
];
