import { v4 as uuid } from 'uuid';

export const mobileKeyIssuanceSummary = [
	{
		id: uuid(),
		email: 'ekaterina.tankova@devias.io',
		name: 'Ekaterina Tankova',
		guestType: 'primary',
		requestedOn: 1555016400000,
		requestStatus: 'Approved',
		responseDateTime: 1555016400000,
		responseBy: 'Admin',
		comment: '',
	},
	{
		id: uuid(),
		email: 'ekaterina.tankova@devias.io',
		name: 'Ekaterina Tankova',
		guestType: 'primary',
		requestedOn: 1555016400000,
		requestStatus: '',
		responseDateTime: 1555016400000,
		responseBy: 'Admin',
		comment: '',
	},
	{
		id: uuid(),
		email: 'ekaterina.tankova@devias.io',
		name: 'Ekaterina Tankova',
		guestType: 'primary',
		requestedOn: 1555016400000,
		requestStatus: 'Revoked',
		responseDateTime: 1555016400000,
		responseBy: 'Admin',
		comment: '',
	},
	{
		id: uuid(),
		email: 'ekaterina.tankova@devias.io',
		name: 'Ekaterina Tankova',
		guestType: 'primary',
		requestedOn: 1555016400000,
		requestStatus: 'Rejected',
		responseDateTime: 1555016400000,
		responseBy: 'Admin',
		comment: '',
	},
];
